---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    package:
      update_cache: yes
    changed_when: false   

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations  
